/*
 * Copyright 2013 Netflix, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.netflix.suro.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServiceStatus implements org.apache.thrift.TEnum {
  DEAD(0),
  STARTING(1),
  ALIVE(2),
  STOPPING(3),
  STOPPED(4),
  WARNING(5);

  private final int value;

  private ServiceStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServiceStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return DEAD;
      case 1:
        return STARTING;
      case 2:
        return ALIVE;
      case 3:
        return STOPPING;
      case 4:
        return STOPPED;
      case 5:
        return WARNING;
      default:
        return null;
    }
  }
}
